# Generated by Django 5.0.4 on 2024-06-21 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0020_alter_feedback_options_alter_order_options_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Order status', 'verbose_name_plural': 'Order statuses'},
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_statuses', to='orders_app.order'),
        ),
    ]
