# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
#github: [arrkpong]

# Replace with a single Patreon username
#patreon: user_patreon

# Replace with a single Open Collective username
#open_collective: user_open_collective

# Replace with a single Ko-fi username
#ko_fi: user_kofi

# Replace with a single Tidelift platform-name/package-name e.g., npm/babel
#tidelift: npm/babel

# Replace with a single Community Bridge project-name e.g., cloud-foundry
#community_bridge: cloud-foundry

# Replace with a single Liberapay username
#liberapay: user_liberapay

# Replace with a single IssueHunt username
#issuehunt: user_issuehunt

# Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
#lfx_crowdfunding: cloud-foundry

# Replace with a single Polar username
#polar: user_polar

# Replace with a single Buy Me a Coffee username
buy_me_a_coffee: arrkpong

# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
#custom: ['link1', 'link2']
