# Generated by Django 5.0 on 2024-02-16 10:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ราคาบัตร')),
            ],
            options={
                'verbose_name': 'ประเภทราคาบัตร',
                'verbose_name_plural': 'ประเภทราคาบัตร',
            },
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=255, unique=True, verbose_name='ชื่อบัตร')),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำอธิบายสินค้า')),
                ('image', models.ImageField(blank=True, upload_to='card_images', verbose_name='รูปภาพบัตรสินค้า')),
                ('is_popular', models.BooleanField(default=False, verbose_name='สินค้ายอดนิยม')),
            ],
            options={
                'verbose_name': 'ประเภทบัตร',
                'verbose_name_plural': 'ประเภทบัตร',
            },
        ),
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='หมายเลขซีเรียลต้องมี 16 ตัวเลขและเป็นตัวเลขเท่านั้น', regex='^[0-9]{16}$')], verbose_name='เลขบัตร')),
                ('pin', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='รหัส PIN ต้องมี 4 ตัวเลขและเป็นตัวเลขเท่านั้น', regex='^[0-9]{4}$')], verbose_name='รหัส PIN ของบัตร')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งานได้')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพิ่ม')),
                ('card_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_details', to='product_app.cardprice', verbose_name='ประเภทบัตร')),
            ],
            options={
                'verbose_name': 'รายละเอียดบัตร',
                'verbose_name_plural': 'รายละเอียดบัตร',
            },
        ),
        migrations.AddField(
            model_name='cardprice',
            name='card_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_prices', to='product_app.cardtype', verbose_name='ประเภทราคาบัตร'),
        ),
    ]
