# Generated by Django 5.0 on 2024-02-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardprice',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='จำนวนบัตร'),
        ),
    ]
