# Generated by Django 5.0.4 on 2024-04-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_cardprice_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advertisement_images', verbose_name='รูปภาพโฆษณา')),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำอธิบายโฆษณา')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
            ],
            options={
                'verbose_name': 'โฆษณา',
                'verbose_name_plural': 'โฆษณา',
            },
        ),
    ]
