# Generated by Django 5.0.4 on 2024-04-29 02:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='เปอร์เซ็นต์ส่วนลด')),
                ('start_date', models.DateField(verbose_name='วันที่เริ่มต้น')),
                ('end_date', models.DateField(verbose_name='วันที่สิ้นสุด')),
                ('card_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='product_app.cardprice', verbose_name='ราคาบัตร')),
            ],
            options={
                'verbose_name': 'โปรโมชั่น',
                'verbose_name_plural': 'โปรโมชั่น',
            },
        ),
    ]
