# Generated by Django 5.0.4 on 2024-06-21 18:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_promotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Advertisement', 'verbose_name_plural': 'Advertisements'},
        ),
        migrations.AlterModelOptions(
            name='carddetail',
            options={'verbose_name': 'Card Detail', 'verbose_name_plural': 'Card Details'},
        ),
        migrations.AlterModelOptions(
            name='cardprice',
            options={'verbose_name': 'Card Price', 'verbose_name_plural': 'Card Prices'},
        ),
        migrations.AlterModelOptions(
            name='cardtype',
            options={'verbose_name': 'Card Type', 'verbose_name_plural': 'Card Types'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotions'},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Advertisement Description'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='advertisement_images', verbose_name='Advertisement Image'),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='card_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_details', to='product_app.cardprice', verbose_name='Card Price'),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='pin',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='PIN must be 4 digits and numeric only', regex='^[0-9]{4}$')], verbose_name='Card PIN'),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='serial_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Serial number must be 16 digits and numeric only', regex='^[0-9]{16}$')], verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='cardprice',
            name='card_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_prices', to='product_app.cardtype', verbose_name='Card Type'),
        ),
        migrations.AlterField(
            model_name='cardprice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Card Price'),
        ),
        migrations.AlterField(
            model_name='cardprice',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity of Cards'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='card_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Card Name'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='image',
            field=models.ImageField(blank=True, upload_to='card_images', verbose_name='Card Image'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Popular Product'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='card_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='product_app.cardprice', verbose_name='Card Price'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount Percentage'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
