# Generated by Django 5.0.2 on 2024-02-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_orderitem_pin_orderitem_serial_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
    ]
