# Generated by Django 5.0.3 on 2024-03-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=100, verbose_name='Status'),
        ),
    ]
