# Generated by Django 5.0.4 on 2024-04-29 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'คำสั่งซื้อ', 'verbose_name_plural': 'คำสั่งซื้อ'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'รายการคำสั่งซื้อ', 'verbose_name_plural': 'รายการคำสั่งซื้อ'},
        ),
    ]
