# Generated by Django 5.0.4 on 2024-05-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0011_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='วันที่')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ยอดรวมรายได้')),
            ],
            options={
                'verbose_name': 'สรุปรายได้',
                'verbose_name_plural': 'สรุปรายได้',
            },
        ),
    ]
