# Generated by Django 5.0.4 on 2024-05-21 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0014_alter_revenuesummary_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenuesummary',
            name='id',
        ),
        migrations.AlterField(
            model_name='revenuesummary',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orders_app.order', verbose_name='คำสั่งซื้อ'),
        ),
    ]
