# Generated by Django 5.0.4 on 2024-05-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0016_orderrevenuesummary_delete_revenuesummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderrevenuesummary',
            options={'verbose_name': 'สรุปยอดรายวัน', 'verbose_name_plural': 'สรุปยอดรายวัน'},
        ),
        migrations.RemoveField(
            model_name='orderrevenuesummary',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='orderrevenuesummary',
            name='start_date',
        ),
        migrations.AddField(
            model_name='orderrevenuesummary',
            name='date',
            field=models.DateField(null=True, verbose_name='วันที่'),
        ),
        migrations.AddField(
            model_name='orderrevenuesummary',
            name='total_orders',
            field=models.IntegerField(default=0, verbose_name='จำนวนคำสั่งซื้อ'),
        ),
        migrations.AlterField(
            model_name='orderrevenuesummary',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='รายได้รวม'),
        ),
    ]
