# Generated by Django 5.0.4 on 2024-05-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0017_alter_orderrevenuesummary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrevenuesummary',
            name='date',
            field=models.DateField(verbose_name='วันที่'),
        ),
    ]
