# Generated by Django 5.0.4 on 2024-05-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0018_alter_orderrevenuesummary_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderRevenueSummary',
        ),
    ]
