# Generated by Django 5.0.2 on 2024-02-24 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_app', '0002_cardprice_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้างตะกร้า')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้ที่เกี่ยวข้องกับตะกร้า')),
            ],
            options={
                'verbose_name': 'ตะกร้า',
                'verbose_name_plural': 'ตะกร้า',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='จำนวน')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.cardprice', verbose_name='บัตรที่เกี่ยวข้อง')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart_app.cart', verbose_name='ตะกร้าที่เกี่ยวข้อง')),
            ],
            options={
                'verbose_name': 'รายการสินค้าในตะกร้า',
                'verbose_name_plural': 'รายการสินค้าในตะกร้า',
            },
        ),
    ]
