# Generated by Django 5.0.2 on 2024-02-24 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
        ('orders_app', '0002_orderitem_pin_orderitem_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='orders_app.orderitem'),
        ),
    ]
