# Generated by Django 5.0.2 on 2024-02-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_cartitem_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='รหัส PIN'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='เลขบัตร'),
        ),
    ]
