# Generated by Django 5.0.2 on 2024-02-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0003_cartitem_pin_cartitem_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='serial_number',
        ),
    ]
