# Generated by Django 5.0.4 on 2024-05-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read',
        ),
        migrations.AddField(
            model_name='notification',
            name='receive_notification',
            field=models.BooleanField(default=True, verbose_name='Receive Notification'),
        ),
    ]
