# Generated by Django 5.0.4 on 2024-05-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_notification_advertisement_image_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enable_two_factor',
            field=models.BooleanField(default=False, verbose_name='Enable Two-Factor Authentication'),
        ),
    ]
