# Generated by Django 5.0.4 on 2024-05-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_profile_enable_two_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='receive_notification',
        ),
        migrations.AddField(
            model_name='profile',
            name='receive_notification',
            field=models.BooleanField(default=True, verbose_name='Receive Notification'),
        ),
    ]
