# Generated by Django 5.0.4 on 2024-06-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_remove_notification_receive_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='receive_notification',
            field=models.BooleanField(default=True, verbose_name='Receive Notification'),
        ),
    ]
