# Generated by Django 5.0.4 on 2024-06-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_notification_receive_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='enable_two_factor',
            field=models.BooleanField(default=False, verbose_name='Enable Two-factor Authentication'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='receive_notification',
            field=models.BooleanField(default=True, verbose_name='Receive Notifications'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
